research_task:
  description: |
    深入研究主题: {topic}
    
    研究要求：
    1. 收集最新趋势和发展动态（近6个月内的信息）
    2. 获取权威数据和统计信息
    3. 搜集专家观点和行业洞察
    4. 查找相关案例研究和实际应用
    5. 识别潜在争议点和不同观点
    6. 验证信息源的可靠性和权威性
    
    特别关注：
    - 确保信息的时效性和准确性
    - 多角度收集信息，避免偏见
    - 记录所有信息来源
  expected_output: |
    一份全面的研究报告，必须包含：
    - 主题核心信息要点（至少10个关键点）
    - 可靠信息源清单（包含URL和发布日期）
    - 支撑数据和统计数字
    - 行业专家引用和观点
    - 相关案例研究
    - 不同观点和争议分析
    - 研究结论和关键洞察
  agent: researcher

analysis_task:
  description: |
    基于研究结果进行深度分析，制定内容策略：
    
    分析维度：
    1. 目标受众画像分析（基于{target_audience}）
    2. 核心主题和子主题识别
    3. 内容结构和逻辑框架设计
    4. 差异化内容策略制定
    5. SEO关键词策略规划
    6. 内容价值点提炼
    
    输出标准：
    - 基于数据驱动的分析结论
    - 清晰的内容组织结构
    - 针对性的策略建议
    
    使用你的专业知识和经验进行分析，无需外部工具。
  expected_output: |
    详细的内容策略分析报告，包含：
    - 目标受众需求分析和痛点识别
    - 结构化内容大纲（包含标题层级）
    - 核心观点和论证逻辑设计
    - SEO关键词列表（主要和长尾关键词）
    - 内容风格和语调建议
    - 差异化价值主张
    - 预期内容效果分析
  agent: analyst
  context: [research_task]

writing_task:
  description: |
    基于策略分析创建{content_type}内容：
    
    写作要求：
    1. 严格按照分析师提供的大纲结构
    2. 符合{target_audience}的阅读习惯和知识水平
    3. 逻辑清晰，表达准确流畅
    4. 自然融入研究数据和实例
    5. 体现独特观点和价值主张
    6. 字数控制在{word_count}字左右
    
    内容标准：
    - 标题具有吸引力和搜索价值
    - 开头能够快速抓住读者注意力
    - 正文逻辑严密，层次分明
    - 结论有力，提供明确的价值或行动建议
  expected_output: |
    完整的{content_type}内容，包含：
    - 吸引人的主标题和副标题
    - 引人入胜的开头段落
    - 结构化的正文内容（包含小标题）
    - 数据、案例和专家观点的自然融入
    - 有力的结论和行动建议
    - 字数符合要求（{word_count}字左右）
    - 语言风格符合目标受众特点
  agent: writer
  context: [research_task, analysis_task]

editing_task:
  description: |
    对内容进行全面编辑和质量优化：
    
    编辑检查项：
    1. 语法、拼写和标点符号检查
    2. 逻辑结构和段落组织优化
    3. 事实准确性和数据验证
    4. SEO元素优化（标题、关键词、元描述）
    5. 可读性和用户体验提升
    6. 格式规范化和一致性检查
    
    质量标准：
    - 零语法和拼写错误
    - 逻辑清晰，表达准确
    - SEO友好且自然
    - 符合目标平台发布标准
  expected_output: |
    编辑完善的最终发布内容，包含：
    - 完全修正的语法、拼写和标点
    - 优化的标题和子标题结构
    - 自然融入的SEO关键词
    - 规范化的格式和排版
    - SEO元描述建议
    - 内容质量评估报告
    - 发布建议和注意事项
  agent: editor
  context: [research_task, analysis_task, writing_task]